/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_watergate_library_LockControlClient */

#ifndef _Callbacks_com_watergate_library_LockControlClient
#define _Callbacks_com_watergate_library_LockControlClient

/*   public native void create(java.lang.String); */
#define CREATE_NAME "create"
/*   public native java.lang.String findLockByName(java.lang.String, int); */
#define FIND_LOCK_BY_NAME_NAME "findLockByName"
/*   public native double getQuota(java.lang.String); */
#define GET_QUOTA_NAME "getQuota"
/*   public native void register_thread(java.lang.String); */
#define REGISTER_THREAD_NAME "register_thread"
/*   public native boolean release(java.lang.String, int); */
#define RELEASE_NAME "release"
/*   public com.watergate.library.LockControlClient$ELockResult getLock(java.lang.String, int, double); */
#define GET_LOCK_NAME "getLock"
/*   public com.watergate.library.LockControlClient$ELockResult getLock(java.lang.String, int, double, long); */
#define GET_LOCK_NAME "getLock"
/*   public com.watergate.library.ObjectState getState(); */
#define GET_STATE_NAME "getState"
#endif //_Callbacks_com_watergate_library_LockControlClient
